### ISSUE TITLE
Bro is everything okay?

### ISSUE THREAD

**Issue by sytemerro** [real0ms/projectV#1]
Hi i'm the guy aceify, If i'm not wrong you are Violet,
i'm asking here cuz you said you deleted all socials and stuff but ik a coder never delete github,
I'm asking if everything is okay please reply if you see this.
Dont do anything stupid please.

**Comment by real0ms** [comment]
Bro firstly how you found my github.....
And i left every socials bc i keep giving motivation to others but now i'm demotivated to do anything i deleted my privious projects already.
I deleted my YT(Most painful for me) , My instagram ,and other social aswell.
I've deleted discord but not the account.
And talking bout stupid things i have nothing to say so please dont ask again.
I may or may not come back to discord ,i've deleted my server also.
And i'm closing this issue please dont issue again without a reason.
![IMG_20210309_122531_459](https://user-images.githubusercontent.com/62207452/110463333-cd9fa000-80f7-11eb-8d21-28ede8e08672.jpg)
![Screenshot_2021_0309_003448](https://user-images.githubusercontent.com/62207452/110463380-d98b6200-80f7-11eb-8d20-7d45ca0c006c.jpg)
![Screenshot_2021_0309_002207](https://user-images.githubusercontent.com/62207452/110463473-f32ca980-80f7-11eb-9467-e59ef3c2b923.jpg)

**Comment by sytemerro** [comment]
Bro please we all miss you, The guy names rainz miss you alot and other peoples aswell please come back😔
You dont need to be active just talk for 5 mins nothing much we need.

**Comment by real0ms** [comment]
> Bro please we all miss you, The guy names rainz miss you alot and other peoples aswell please come back😔
> You dont need to be active just talk for 5 mins nothing much we need.

I'll be back under a week ig i just need some time to recover please tell rainz and who ever missed i also miss them much i'll be back soon✌ but please give me some time. ty❤
